const {DataTypes} = require('sequelize');

module.exports = (sequelize)=>{
    sequelize.define('Cliente',{
        idCliente:{
            type:DataTypes.UUID,
            primaryKey:true,
            defaultValue:DataTypes.UUIDV4,
        },
        nombre:{
            type:DataTypes.STRING,
            allowNull:false,
            defaultValue:'GENERICO',
        },
        apellidoPaterno:{
            type:DataTypes.STRING,
            allowNull:true,
            defaultValue:'',
        },
        apellidoMaterno:{
            type:DataTypes.STRING,
            allowNull:true,
            defaultValue:'',
        },
        dni:{
            type:DataTypes.STRING,
            allowNull:true,
            validate:{
                is:/^\d{8}$/
            },
        },
        ruc:{
            type:DataTypes.STRING,
            allowNull:true,
            validate:{
                is:/^\d{11}$/
            },
        },
        telefono:{
            type:DataTypes.INTEGER,
            allowNull:true,
        },
        eliminado:{
            type:DataTypes.BOOLEAN,
            allowNull:false,
            defaultValue:false,
        },
    },
    {   timestamps:false,
        tableName:'clientes',
    });
};
